// Generated by LiveScript 1.5.0
/**
 * @package Entangled state DHT
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  /*
   * Implements version ? of the specification
   */
  function Wrapper(arrayMapSet, kBucketSync){
    var ArrayMap;
    ArrayMap = arrayMapSet['ArrayMap'];
    /**
     * @constructor
     *
     * @param {number}	size
     *
     * @return {!LRU}
     */
    function LRU(size){
      if (!(this instanceof LRU)) {
        return new LRU(size);
      }
      this._size = size;
      this._map = ArrayMap();
      this._last_key = null;
    }
    LRU.prototype = {
      /**
       * @param {!Uint8Array}			key
       * @param {!Array<!Uint8Array>}	value
       */
      add: function(key, value){
        if (this._map.has(key)) {
          return;
        }
        this._map.set(key, value);
        this._last_key = key;
        if (this._map.size > this._size) {
          this._map['delete'](this._map.keys().next().value);
        }
      }
      /**
       * @param {!Uint8Array}	key
       *
       * @return {!Array<!Uint8Array>}
       */,
      get: function(key){
        return this._map.get(key);
      }
      /**
       * @param {!Uint8Array}	key
       */,
      del: function(key){
        var ref$;
        this._map['delete'](key);
        if (!this._map.has(this._last_key)) {
          this._last_key = (ref$ = Array.from(this._map.keys()))[ref$.length - 1] || null;
        }
      }
      /**
       * @return {Uint8Array} `null` if there are no items
       */,
      last_key: function(){
        return this._last_key;
      }
    };
    /**
     * @constructor
     *
     * @param {!Uint8Array}	id					Own ID
     * @param {number}		bucket_size			Size of a bucket from Kademlia design
     * @param {number}		state_history_size	How many versions of local history will be kept
     *
     * @return {!DHT}
     */
    function DHT(id, bucket_size, state_history_size){
      if (!(this instanceof DHT)) {
        return new DHT(id, bucket_size, state_history_size);
      }
      this._id = id;
      this._state = LRU(state_history_size);
      this._insert_state(new Map);
    }
    DHT.prototype = {
      /**
       * @param {!Uint8Array} id				Id of a peer
       * @param {!Uint8Array} state_version	State version of a peer
       */
      'set_peer': function(id, state_version){
        var state;
        state = this['get_state']()[1];
        state.set(id, state_version);
        this._insert_state(state);
      }
      /**
       * @param {!Uint8Array} id Id of a peer
       */,
      'del_peer': function(id){
        var state;
        state = this['get_state']()[1];
        if (!state.has(id)) {
          return;
        }
        state['delete'](id);
        this._insert_state(state);
      }
      /**
       * @param {Uint8Array=} state_version	Specific state version or latest if `null`
       *
       * @return {!Array} `[state_version, state]`, where `state_version` is a Merkle Tree root of the state and `state` is a `Map` with peers as keys and their state versions as values
       */,
      'get_state': function(state_version){
        state_version == null && (state_version = null);
        state_version = state_version || this._state.last_key();
        return [state_version, ArrayMap(Array.from(this._state.get(version)))];
      }
      /**
       * @param {!Map}	new_state
       */,
      _insert_state: function(new_state){
        var items, ref$, items_count, state_version;
        items = (ref$ = []).concat.apply(ref$, Array.from(new_state));
        items_count = items.length;
        items.length = Math.ceil(Math.log2(items_count + 1)) - items_count;
        items.fill(this._id, items_count);
        state_version = merkleTree(items);
        this._state.add(state_version, new_state);
      }
    };
    Object.defineProperty(DHT.prototype, 'constructor', {
      value: DHT
    });
    return DHT;
  }
  if (typeof define === 'function' && define['amd']) {
    define(['array-map-set', 'k-bucket-sync'], Wrapper);
  } else if (typeof exports === 'object') {
    module.exports = Wrapper(require('array-map-set'), require('k-bucket-sync'));
  } else {
    this['detox_transport'] = Wrapper(this['array_map_set'], this['k_bucket_sync']);
  }
}).call(this);
